### ISSUE TITLE
github star count broken during loading

### ISSUE THREAD

**Issue by davidszotten** [nameko/nameko.io#2]
Hi,

firstly, thanks for all the work on the site, it looks amazing

small bug: during loading, the github stars button if broken i think. see screenshots from the chrome performance tab

<img width="369" alt="screen shot 2018-08-15 at 21 21 01" src="https://user-images.githubusercontent.com/412005/44171064-373aa780-a0d1-11e8-9ffe-c5a60cd90e38.png">
<img width="377" alt="screen shot 2018-08-15 at 21 21 09" src="https://user-images.githubusercontent.com/412005/44171066-37d33e00-a0d1-11e8-8768-962fdb9932eb.png">
<img width="364" alt="screen shot 2018-08-15 at 21 21 15" src="https://user-images.githubusercontent.com/412005/44171067-37d33e00-a0d1-11e8-9aa8-8ca396d4b4b2.png">
<img width="392" alt="screen shot 2018-08-15 at 21 21 21" src="https://user-images.githubusercontent.com/412005/44171068-37d33e00-a0d1-11e8-91fc-dafd97acf4b3.png">

**Comment by kylesome** [comment]
Hi @davidszotten , thanks for logging the issue 🙂 yeah I agree it seems be floated left until the request for the number of stars comes back. Might need to change the order of some components. I'll look into it 👍

**Comment by kylesome** [comment]
@davidszotten I believe this should be fixed now, try a couple of refreshes and let me know if there are any issues
